project:
  type: book


book:
  title: "Thesis DOCAS"
  subtitle: "Format to write Thesis to PhD Antarctic and SubAntartic Science Program"
  author: "Mauro Mardones"
  date: "03 March 2023"
  chapters:
    - index.qmd
    - intro.qmd
    - method.qmd
    - summary.qmd
    - references.qmd
    #- ANEXO 1. Time Series Analysis

bibliography: [DOCAS.bib, references.bib]
csl: apa.csl
fig-align: center
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

